---
title: "assumption_testing"
author: "Dominik Dianovics"
format: html
---

# Researcher burnout and questionable research practice pilot data diagnostic checks

## Testing reliability, validity, and dimensionality of the used scales

### Loading packages

```{r}
library(tidyverse)
library(here)

data_path <- here("data")
```

### Loading data

```{r}
processed = read_csv(here::here("data/processed/aggregated_data.csv"))
```

### Testing reliability: Checking McDonald's omega (Cronbach's alpha alternative)

```{r}
items = c("brt_", "pps_", "ppa_", "ppr_", "wld_", "soc_",
            "opp_", "wlb_", "jis_", "qrp_", "inf_", "mng_",
            "rla_", "rlc_", "pay_", "tol_", "gnl_")

omega_function <- function(data, survey) {
  items <- data %>%
    dplyr::select(starts_with(survey))

  omega_out <- psych::omega(
    items,
    nfactors = 1,
    plot = FALSE
  )

  data.frame(
    survey = survey,
    omega_total = omega_out$omega.tot
  )
}

omega_results <- data.frame()

for (survey in surveys) {
  omega_result <- omega_function(processed, survey)
  omega_results <- rbind(omega_results, omega_result)
}

# Second-order factor analyses for each survey
WLD + PPA + PPS + AMB + CON + WLB
OPP + MNG + INF + SOC + PPR + SEC

job_demands = c("ppqr_stress", "copsoq_workload", "ppqr_attitude", "role_conflict","role_conflict", "wlbm")
job_resources = c("ppqr_resources",  "copsoq_soc_sup", "copsoq_oppor", "jis", "copsoq_infl", "copsoq_meaning")

omega()

```

# Testing convergent validity with CFA
```{r}
fit_single_factor_cfa <- function(data, survey_prefix) {
  
  items <- names(data)[startsWith(names(data), survey_prefix)]
  
  # Safety check
  if (length(items) < 3) {
    warning(paste("Survey", survey_prefix, "has fewer than 3 items"))
    return(NULL)
  }
  
  # Build CFA model string
  model <- paste0(
    "factor =~ ",
    paste(items, collapse = " + ")
  )
  
  fit <- cfa(
    model,
    data = data,
    estimator = "MLR",
    std.lv = TRUE,
    missing = "fiml"
  )
  
  list(
    survey = survey_prefix,
    fit = fit
  )
}

cfa_results <- map(
  surveys,
  ~ fit_single_factor_cfa(processed, .x)
)

# Remove NULLs (if any survey had too few items)
cfa_results <- compact(cfa_results)

loadings_table <- map_df(
  cfa_results,
  function(x) {
    standardizedSolution(x$fit) |>
      filter(op == "=~") |>
      mutate(survey = x$survey) |>
      dplyr::select(survey, indicator = rhs, loading = est.std)
  }
)

compute_ave <- function(fit) {
  
  pe <- parameterEstimates(fit)
  
  loadings <- pe |>
    filter(op == "=~")
  
  errors <- pe |>
    filter(op == "~~", lhs == rhs, lhs %in% loadings$rhs)
  
  lambda_sq <- loadings$est^2
  theta     <- errors$est
  
  sum(lambda_sq) / (sum(lambda_sq) + sum(theta))
}


ave_table <- map_df(
  cfa_results,
  function(x) {
    tibble(
      survey = x$survey,
      AVE = compute_ave(x$fit)
    )
  }
)
```

# Testing divergent validity
```{r}
build_multifactor_cfa <- function(data, surveys) {
  
  model_parts <- map(
    surveys,
    function(survey) {
      items <- names(data)[startsWith(names(data), survey)]
      
      if (length(items) >= 3) {
        paste0(survey, " =~ ", paste(items, collapse = " + "))
      } else {
        NULL
      }
    }
  )
  
  model_parts <- compact(model_parts)
  
  paste(model_parts, collapse = "\n")
}

multi_cfa_model <- build_multifactor_cfa(processed, surveys)

multi_cfa_fit <- cfa(
  multi_cfa_model,
  data = processed,
  estimator = "MLR",
  std.lv = TRUE,
  missing = "fiml"
)

latent_correlations <- inspect(multi_cfa_fit, "cor.lv")
latent_correlations

htmt(multi_cfa_model, processed)


jdr_measurement_model <- '
  # First-order factors
  WLD =~ copsoq_workload_1 + copsoq_workload_2 + copsoq_workload_3 + copsoq_workload_4
  PPA =~ ppqr_attitude_7 + ppqr_attitude_8 + ppqr_attitude_9 + ppqr_attitude_10 + ppqr_attitude_11 + ppqr_attitude_12
  PPS =~ ppqr_stress_1 + ppqr_stress_2 + ppqr_stress_3 + ppqr_stress_4 + ppqr_stress_5 + ppqr_stress_6
  AMB =~ role_ambiguity_01 + role_ambiguity_02 + role_ambiguity_03 + role_ambiguity_04 + role_ambiguity_05 + role_ambiguity_06
  CON =~ role_conflict_07 + role_conflict_08 + role_conflict_09 + role_conflict_10 + role_conflict_11 + role_conflict_12
  WLB =~ wlbm_1 + wlbm_2 + wlbm_3 + wlbm_4

  OPP =~ copsoq_oppor_1 + copsoq_oppor_2 + copsoq_oppor_3
  MNG =~ copsoq_meaning_1 + copsoq_meaning_2
  INF =~ copsoq_infl_1 + copsoq_infl_2 + copsoq_infl_3 + copsoq_infl_4
  SOC =~ copsoq_soc_sup_1 + copsoq_soc_sup_2 + copsoq_soc_sup_3 + copsoq_soc_sup_4
  SEC =~ jis_1 + jis_2 + jis_3 + jis_4
  PPR =~ ppqr_resources_13 + ppqr_resources_14 + ppqr_resources_15 + ppqr_resources_16 + ppqr_resources_17 + ppqr_resources_18

  # Second-order factors
  job_demands =~ WLD + PPA + PPS + AMB + CON + WLB
  job_resources =~ OPP + MNG + INF + SOC + SEC + PPR
'

htmt(jdr_measurement_model, processed)


```