---
title: "aggregation"
author: "Dominik Dianovics"
format: html
---

# Researcher burnout and questionable research practice pilot data cleaning

## Processed to aggregated data

### Loading packages

```{r}
library(tidyverse)
library(here)
library(purrr)
library(psych)
library(naniar)

data_path <- here("data")
```

### Loading data

```{r}
processed = read_csv(here::here("data/processed/processed_data.csv"))
```

### Checking missingness

```{r}
surveys = c("brt", "wld", "scs", "scc",
            "opp", "wlb", "sec", "inf", "mng", "pps", "ppa", "ppr",
            "rla", "rlc")

missingness_summary = processed %>%
  dplyr::select(starts_with(surveys)) %>%
  summarise(across(everything(), ~ mean(is.na(.)) * 100)) %>%
  pivot_longer(everything(), names_to = "item", values_to = "missingness_percentage")

processed %>%
  dplyr::select(starts_with(surveys)) %>%
  naniar::mcar_test()

# Case-level missingness
processed %>%
  dplyr::select(starts_with(surveys)) %>%
  naniar::miss_case_summary()

# Variable-level missingness
processed %>%
  dplyr::select(starts_with(surveys)) %>%
  naniar::miss_var_summary()

processed %>%
  dplyr::select(starts_with(surveys)) %>%
  naniar::gg_miss_var()

# Percentage of people having at least one missing value

processed %>%
  dplyr::select(starts_with(surveys)) %>%
  summarise(missing_any = sum(if_any(everything(), is.na)))

# Looking at missingness patterns, I assume there has been an error in the survey programming, as the first 8 rows all have no brt_3 and brt_4 responses, after that the same relationship does not appear.


# Total missing values
processed %>%
  dplyr::select(starts_with(surveys)) %>%
  summarise(total_missing = sum(is.na(.)),
            total_values = nrow(.) * ncol(.),
            missing_percentage = (total_missing / total_values) * 100)

# Most of the missingness comes from the first 8 individuals and the QRP questions, without them the missingness is very low

processed_filtered = processed
```

### Aggregating data

```{r}
aggregate_function <- function(data, survey) {
  data %>%
    group_by(anonym_id) %>%
    summarize(
      "{survey}" := {
        vars <- across(starts_with(survey))
        round(rowMeans(vars),3 )
      }
    )
}

for (survey in surveys){
  assign(paste0(survey, "_aggregated"), aggregate_function(processed_filtered, survey))
}

aggregated_datasets <- mget(ls(pattern = "_aggregated$"))
aggregated_data <- reduce(aggregated_datasets, left_join, by = "anonym_id")
```

#Joining aggregate data with item-level and descriptives

```{r}
item_and_aggregate_data = processed_filtered %>% 
  left_join(aggregated_data, by = "anonym_id") %>% 
  relocate(anonym_id, gender, title, discipline, last_published, academia_length, phd_dissertation, .before = brt_1)
```

#Save data

```{r}
write_csv(item_and_aggregate_data, here::here("data/processed/aggregated_data.csv"))
```
