---
title: "raw_to_clean_data_code"
format: html
---

# Researcher burnout and questionable research practice pilot data cleaning

## Raw to clean data

### Installing packages

```{r echo=FALSE, output=FALSE}
library(tidyverse)
library(here)
data_path <- here("data")
```

### Importing data

```{r echo=FALSE}
raw_data_01 = read.csv(here::here("data/raw/october_17_decisionlab.csv"))
raw_data_02 = read.csv(here::here("data/raw/october_17_aczellab.csv"))

if (identical(names(raw_data_01), names(raw_data_02))) {
  cat("The column names are identical.\n")
} else {
  cat("The column names are different.\n")
}

raw_data = raw_data_01 |> 
  bind_rows(raw_data_02) %>% 
  dplyr::select(-open_time)
```

### Filtering out irrelevant data for analysis

```{r}
raw_data_filtered = raw_data |> 
  dplyr::select(-StartDate, 
         -EndDate,
         -Status,
         -Duration..in.seconds.,
         -Progress,
         -RecordedDate,
         -ResponseId,
         -UserLanguage,
         -DistributionChannel)

meta_data = raw_data |> 
  dplyr::select(StartDate, 
         EndDate,
         Status,
         Duration..in.seconds.,
         Progress,
         RecordedDate,
         ResponseId,
         UserLanguage,
         DistributionChannel)
```

### Creating notebook

```{r}
codebook = raw_data_filtered[1, , drop = FALSE]
codebook = codebook |> 
  pivot_longer(everything(), names_to = "variable", values_to = "description") %>% 
  separate(
    col = description,
    into = c("context", "question"),
    sep = " - "
  )
```

### Unifying syntax

```{r}
raw_data_unified = raw_data_filtered |> 
  rename_with(tolower) |> 
  slice(-c(1, 2))
```

### Checking for exclusion criteria

```{r}
# Removing participants based on exclusion criteria
raw_data_valid = raw_data_unified %>%  
  filter(finished == "True") %>%  
  filter(consent == "Yes") %>%  
  filter(academic_yes_no == "Yes") %>%  
  filter(research_yes_no == "Yes") %>% 
  dplyr::select(-finished, -consent, -academic_yes_no, -research_yes_no)


# Counting valid responses
valid_respones = raw_data_unified %>%  
  summarize(n_all = n(),
            n_finished = sum(finished == "True"),
            n_consent = sum(consent == "Yes"),
            n_academic = sum(academic_yes_no == "Yes"),
            n_research = sum(research_yes_no == "Yes"))
```

### Creation of anonym id

```{r}
raw_data_anonymized = raw_data_valid %>%  
  mutate(anonym_id = row_number()) 
```

### Locate attention check questions

```{r}
#For copsoq_wokload_5, "Rarely" is the correct answer
#For attention_2, "Strongly agree" is the correct answer

raw_data_attention = raw_data_anonymized |> 
  rename(attention_1 = copsoq_workload_5) |>
  dplyr::select(attention_1, attention_2, anonym_id)

attention_check = raw_data_attention |> 
  mutate(attention_1 = if_else(attention_1 == "Rarely", 1, 0),
         attention_2 = if_else(attention_2 == "Strongly agree", 1, 0)) |> 
  mutate(attention = ifelse(attention_1 == 0 & attention_2 == 0, "Failed", "Passed")) |> 
  dplyr::select(attention, anonym_id)

raw_data_valid = raw_data_anonymized |> 
  left_join(attention_check, by = "anonym_id") %>% 
  filter(attention != "Failed") %>% 
  dplyr::select(-copsoq_workload_5, -attention_2, -attention)
```

# Saving data

```{r}
write.csv(raw_data_valid, here::here("data/processed/raw_to_clean_data.csv"), row.names = FALSE)
write.csv(codebook, here::here("data/processed/codebook.csv"), row.names = FALSE)
write.csv(meta_data, here::here("data/processed/meta_data.csv"), row.names = FALSE)
write.csv(valid_respones, here::here("data/processed/participant_checks.csv"), row.names = FALSE)
```
